#!/bin/sh
ext=-json
echo 01-servercurltest
01-servercurltest.sh >01-result-tmp
diff 01-expected$ext 01-result-tmp

echo 02-serverCombinedtest
02-serverCombinedtest.sh >02-result-tmp
diff 02-expected$ext 02-result-tmp

echo 03-loaditest2
03-loaditest2.sh >03-result-tmp
diff 03-expected$ext 03-result-tmp

echo 04-server-grantdeny-test
04-server-grantdeny-test.sh >04-result-tmp
diff 04-expected$ext 04-result-tmp

echo 05-delete-multiple-test
05-add-delete-multiple-test.sh >05-result-tmp
diff 05-expected$ext 05-result-tmp

echo 06-server-new-feature-test
06-server-new-feature-test.sh >06-result-tmp
diff 06-expected$ext 06-result-tmp

echo 07-context-change-test
07-context-change-test.sh >07-result-tmp
diff 07-expected$ext 07-result-tmp

echo 07c-conditional-query-test
07c-conditional-query-test.sh >07c-result-tmp
diff 07c-expected$ext 07c-result-tmp

echo 08-event-triggered-response-test
08-event-triggered-response-test.sh >08-result-tmp
diff 08-expected$ext 08-result-tmp

echo 09-cme-context-reg-test
09-cme-context-reg-test.sh 8002 >09-result-tmp
diff 09-expected$ext 09-result-tmp

echo 10-servercurltest-accessm
10-servercurltest-accessm.sh >10-result-tmp
diff 10-expected$ext 10-result-tmp

echo 11-servercurltest-accessmc
11-servercurltest-accessmc.sh >11-result-tmp
diff 11-expected$ext 11-result-tmp

echo 12-users
12-users.sh >12-result-tmp
diff 12-expected$ext 12-result-tmp

echo 13-market-policy
13-market-policy.sh >13-result-tmp
diff 13-expected$ext 13-result-tmp

echo 14-market-policy
14-market-policy.sh >14-result-tmp
diff 14-expected$ext 14-result-tmp

echo 14c-market-policy
14c-market-policy.sh >14c-result-tmp
diff 14c-expected$ext 14c-result-tmp

echo 17-dplp-query
17-dplp-query.sh >17-result-tmp
diff 17-expected$ext 17-result-tmp

echo 18-consent-meta
18-consent-meta.sh >18-result-tmp
diff 18-expected$ext 18-result-tmp

echo 19-consent-example-full
19-consent-example-full.sh >19-result-tmp
diff 19-expected$ext 19-result-tmp

echo 20-consent-example-full-meta
20-consent-example-full-meta.sh >20-result-tmp
diff 20-expected$ext 20-result-tmp
